#!/bin/bash
set -euo pipefail

# ZeroClawed Binary Installer
# Builds, deploys, and configures the zeroclawed binary
#
# Usage:
#   scripts/install-zeroclawed.sh <action> [host1 host2 ...]
#
# Actions:
#   build     Build release binary
#   deploy    Deploy binary + config + service
#   install   Build + deploy + verify (full setup)
#   verify    Check service health
#   restart   Restart service
#   status    Show service status
#
# Examples:
#   scripts/install-zeroclawed.sh install 192.168.1.127
#   scripts/install-zeroclawed.sh install 192.168.1.127 192.168.1.49
#   scripts/install-zeroclawed.sh deploy 192.168.1.127
#   scripts/install-zeroclawed.sh verify 192.168.1.127

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INSTALL_DIR="/opt/zeroclawed"
CONFIG_DIR="/etc/zeroclawed"
SSH_KEY="${SSH_KEY:-~/.ssh/id_ed25519}"

# ── Target resolution ──────────────────────────────────────────────
ACTION="${1:-help}"
shift || true

if [ $# -gt 0 ]; then
    TARGETS=("$@")
elif [ -f "$(dirname "$0")/targets.txt" ]; then
    mapfile -t TARGETS < <(grep -v '^#' "$(dirname "$0")/targets.txt" | grep -v '^$')
else
    echo "No targets specified. Usage:"
    echo "  $0 <action> host1 [host2 ...]"
    exit 1
fi

echo "=== ZeroClawed Installer ==="
echo "Action: $ACTION"
echo "Targets: ${TARGETS[*]}"
echo ""

# ── Helpers ────────────────────────────────────────────────────────
run_on() {
    local host="$1"; shift
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no -o ConnectTimeout=10 "root@$host" "$@"
}

copy_to() {
    local src="$1" host="$2" dst="$3"
    scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$src" "root@$host:$dst"
}

generate_config() {
    cat << 'DEFAULT_CONFIG'
# ZeroClawed Configuration
# Generated by install-zeroclawed.sh
#
# See crates/zeroclawed/examples/config.toml for all options

# ── Gateway ─────────────────────────────────────────────────────
[gateway]
listen_addr = "0.0.0.0:18789"
forward_to = "http://127.0.0.1:8080"

# ── Identity ────────────────────────────────────────────────────
[identity]
header = "X-Forwarded-For"
strategy = "extract-first"

# ── Models ──────────────────────────────────────────────────────
# Remote models
[[models]]
name = "kimi-k2"
provider = "moonshot"
model_id = "kimi-k2"
api_key_env = "KIMI_API_KEY"

[[models]]
name = "gpt-4o-mini"
provider = "openai"
model_id = "gpt-4o-mini"
api_key_env = "OPENAI_API_KEY"

[[models]]
name = "claude-sonnet-4"
provider = "anthropic"
model_id = "claude-sonnet-4-20250514"
api_key_env = "ANTHROPIC_API_KEY"

# Local models (vLLM)
[[models]]
name = "llama-3-70b"
provider = "vllm"
model_id = "llama-3-70b-instruct"
base_url = "http://127.0.0.1:8000/v1"

# ── Adversary Detection ────────────────────────────────────────
# Channel scanning: per-channel opt-in (default: false)
# HTTP proxy: always-on (no config needed)
#
# To enable channel scanning, add to each [[channels]] section:
#   scan_messages = true
#
# Domain skip protection (HTTP proxy only):
#   [adversary]
#   skip_protection = ["*.trusted.com", "api.internal"]
#   profile = "balanced"  # open|balanced|hardened|paranoid

# ── Channels ────────────────────────────────────────────────────
[[channels]]
kind = "whatsapp"
enabled = true
scan_messages = false  # Set to true to scan WhatsApp messages

[channels.webhook]
listen_addr = "0.0.0.0:8443"
token = "${WHATSAPP_WEBHOOK_TOKEN:-}"
secret = "${WHATSAPP_WEBHOOK_SECRET:-}"

[[channels]]
kind = "signal"
enabled = true
scan_messages = false  # Set to true to scan Signal messages

[channels.webhook]
listen_addr = "0.0.0.0:8444"
token = "${SIGNAL_WEBHOOK_TOKEN:-}"

[[channels]]
kind = "telegram"
enabled = true
scan_messages = false  # Set to true to scan Telegram messages

[channels.webhook]
listen_addr = "0.0.0.0:8445"
token = "${TELEGRAM_BOT_TOKEN:-}"

[[channels]]
kind = "matrix"
enabled = false
scan_messages = false

[channels.webhook]
listen_addr = "0.0.0.0:8446"
token = "${MATRIX_TOKEN:-}"
DEFAULT_CONFIG
}

# ── Actions ────────────────────────────────────────────────────────
build() {
    echo "Building release binary..."
    cd "$PROJECT_ROOT"
    cargo build --release -p zeroclawed 2>&1 | tail -5
    echo "Build complete."
}

deploy_host() {
    local host="$1"
    echo "── Deploying to $host ──"

    # Create dirs
    run_on "$host" "mkdir -p $INSTALL_DIR/bin $CONFIG_DIR" 2>&1 || {
        echo "  ⚠ Cannot reach $host, skipping"
        return 1
    }

    # Copy binary
    copy_to "$PROJECT_ROOT/target/release/zeroclawed" "$host" "$INSTALL_DIR/bin/zeroclawed" 2>&1
    run_on "$host" "chmod +x $INSTALL_DIR/bin/zeroclawed"

    # Generate default config if it doesn't exist
    if ! run_on "$host" "test -f $CONFIG_DIR/config.toml" 2>/dev/null; then
        echo "  Generating default config.toml..."
        generate_config | run_on "$host" "cat > $CONFIG_DIR/config.toml"
        echo "  ⚠  Edit $CONFIG_DIR/config.toml on $host to set API keys and enable channels"
    else
        echo "  Config already exists — not overwriting"
    fi

    # Install systemd service
    run_on "$host" "cat > /etc/systemd/system/zeroclawed.service << 'EOF'
[Unit]
Description=ZeroClawed Gateway
After=network.target

[Service]
Type=simple
ExecStart=$INSTALL_DIR/bin/zeroclawed --config $CONFIG_DIR/config.toml
Environment=RUST_LOG=zeroclawed=info
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable zeroclawed
systemctl restart zeroclawed" 2>&1

    echo "  ✅ Deployed to $host"
}

verify_host() {
    local host="$1"
    echo "── Verifying $host ──"

    echo -n "  zeroclawed:  "
    run_on "$host" "systemctl is-active zeroclawed 2>/dev/null" || echo "❌ not running"

    echo -n "  gateway:     "
    run_on "$host" "curl -s http://127.0.0.1:18789/health" 2>/dev/null || echo "❌ not responding"

    echo -n "  config:      "
    if run_on "$host" "test -f $CONFIG_DIR/config.toml" 2>/dev/null; then
        echo "✅ exists"
    else
        echo "❌ missing"
    fi
}

# ── Main ───────────────────────────────────────────────────────────
case "$ACTION" in
    install)
        build
        for host in "${TARGETS[@]}"; do
            deploy_host "$host" || true
        done
        echo ""
        for host in "${TARGETS[@]}"; do
            verify_host "$host"
        done
        echo ""
        echo "=== Installation Complete ==="
        echo "Configure API keys on each host:"
        echo "  export KIMI_API_KEY=..."
        echo "  export OPENAI_API_KEY=sk-..."
        echo "  export ANTHROPIC_API_KEY=sk-ant-..."
        echo ""
        echo "Enable channel scanning in $CONFIG_DIR/config.toml:"
        echo "  scan_messages = true  # per [[channels]] section"
        ;;
    deploy)
        for host in "${TARGETS[@]}"; do
            deploy_host "$host" || true
        done
        ;;
    build)
        build
        ;;
    verify)
        for host in "${TARGETS[@]}"; do
            verify_host "$host"
        done
        ;;
    restart)
        for host in "${TARGETS[@]}"; do
            echo "Restarting zeroclawed on $host..."
            run_on "$host" "systemctl restart zeroclawed" 2>&1 || echo "  ⚠ $host unreachable"
        done
        ;;
    status)
        for host in "${TARGETS[@]}"; do
            echo "── $host ──"
            run_on "$host" "systemctl is-active zeroclawed 2>/dev/null" || echo "  unreachable"
        done
        ;;
    help|*)
        cat << 'USAGE'
ZeroClawed Binary Installer

Usage:
  scripts/install-zeroclawed.sh <action> [host1 host2 ...]

Actions:
  install   Build + deploy + configure + verify (full setup)
  deploy    Deploy binary + config + service (skip build)
  build     Just build release binary
  verify    Check service health on targets
  restart   Restart service on targets
  status    Show service status on targets
  help      Show this help

Examples:
  scripts/install-zeroclawed.sh install 192.168.1.127
  scripts/install-zeroclawed.sh deploy 192.168.1.127
  scripts/install-zeroclawed.sh verify 192.168.1.127
  scripts/install-zeroclawed.sh status

  # Use targets.txt
  echo "192.168.1.127" > scripts/targets.txt
  scripts/install-zeroclawed.sh install

  # Set custom SSH key
  SSH_KEY=~/.ssh/id_ed25519_librarian scripts/install-zeroclawed.sh install 192.168.1.127

Channel Scanning Configuration:
  The install script generates a default config.toml with scan_messages = false
  for all channels. To enable scanning, edit config.toml on the target host:
    [[channels]]
    kind = "whatsapp"
    scan_messages = true  # Enable adversary detection for WhatsApp

  HTTP proxy scanning is always-on (no config needed).
USAGE
        ;;
esac
