#!/bin/bash
set -euo pipefail

# Calciforge Binary Installer
# Builds, deploys, and configures the calciforge binary
#
# Usage:
#   scripts/install-calciforge.sh <action> [host1 host2 ...]
#
# Actions:
#   build     Build release binary
#   deploy    Deploy binary + config + service
#   install   Build + deploy + verify (full setup)
#   verify    Check service health
#   restart   Restart service
#   status    Show service status
#
# Examples:
#   scripts/install-calciforge.sh install 192.168.1.127
#   scripts/install-calciforge.sh install 192.168.1.127 192.168.1.49
#   scripts/install-calciforge.sh deploy 192.168.1.127
#   scripts/install-calciforge.sh verify 192.168.1.127

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INSTALL_DIR="/opt/calciforge"
CONFIG_DIR="/etc/calciforge"
SSH_KEY="${SSH_KEY:-$HOME/.ssh/id_ed25519}"

# ── Target resolution ──────────────────────────────────────────────
ACTION="${1:-help}"
shift || true

if [ $# -gt 0 ]; then
    TARGETS=("$@")
elif [ -f "$(dirname "$0")/targets.txt" ]; then
    mapfile -t TARGETS < <(grep -v '^#' "$(dirname "$0")/targets.txt" | grep -v '^$')
else
    echo "No targets specified. Usage:"
    echo "  $0 <action> host1 [host2 ...]"
    exit 1
fi

echo "=== Calciforge Installer ==="
echo "Action: $ACTION"
echo "Targets: ${TARGETS[*]}"
echo ""

# ── Helpers ────────────────────────────────────────────────────────
run_on() {
    local host="$1"; shift
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10 "root@$host" "$@"
}

copy_to() {
    local src="$1" host="$2" dst="$3"
    scp -i "$SSH_KEY" -o StrictHostKeyChecking=accept-new "$src" "root@$host:$dst"
}

generate_config() {
    cat << 'DEFAULT_CONFIG'
# Calciforge Configuration
# Generated by install-calciforge.sh
#
# See crates/calciforge/examples/config.toml for all options

[calciforge]
version = 1

# ── Context (conversation ring buffer) ─────────────────────────
[context]
buffer_size = 20
inject_depth = 5

# ── Model Shortcuts ────────────────────────────────────────────
# Use !model <alias> to quickly switch models
[[model_shortcuts]]
alias = "sonnet"
model = "anthropic/claude-sonnet-4.6"

[[model_shortcuts]]
alias = "fast"
model = "gemini/gemini-2.5-flash"

# ── Security / Adversary Detection ─────────────────────────────────
[security]
profile = "balanced"  # open | balanced | hardened | paranoid
scan_outbound = false

# ── Channels ────────────────────────────────────────────────────
# WhatsApp channel (requires ZeroClaw/OpenClaw gateway with WA session)
[[channels]]
kind = "whatsapp"
enabled = false
scan_messages = false
# zeroclaw_endpoint = "http://127.0.0.1:18789"
# zeroclaw_auth_token = "YOUR_ZEROCLAW_TOKEN"
# webhook_listen = "0.0.0.0:18795"
# webhook_path = "/webhooks/whatsapp"
# allowed_numbers = ["+15555550001"]

# Signal channel (requires ZeroClaw/OpenClaw gateway with Signal session)
[[channels]]
kind = "signal"
enabled = false
scan_messages = false
# zeroclaw_endpoint = "http://127.0.0.1:18789"
# zeroclaw_auth_token = "YOUR_ZEROCLAW_TOKEN"
# webhook_listen = "0.0.0.0:18796"
# webhook_path = "/webhooks/signal"
# allowed_numbers = ["+15555550001"]

# Telegram channel (direct bot integration)
[[channels]]
kind = "telegram"
enabled = false
scan_messages = false
# bot_token_file = "/etc/calciforge/telegram_bot_token.txt"

# Matrix channel (direct Matrix bot)
[[channels]]
kind = "matrix"
enabled = false
scan_messages = false
# homeserver = "https://matrix.org"
# access_token_file = "/etc/calciforge/matrix_token.txt"
# room_id = "!YOUR_ROOM:matrix.org"

# ── Identities ─────────────────────────────────────────────────
# Define users and their channel aliases
# [[identities]]
# id = "brian"
# display_name = "Brian"
# aliases = [
#     { channel = "whatsapp", id = "+15555550001" },
#     { channel = "signal", id = "+15555550001" },
# ]

# ── Agents ─────────────────────────────────────────────────────
# [[agents]]
# id = "main"
# model = "anthropic/claude-sonnet-4.6"
# system_prompt = "You are a helpful assistant."

# ── Routing ────────────────────────────────────────────────────
# [[routing]]
# identity = "brian"
# default_agent = "main"
DEFAULT_CONFIG
}

# ── Actions ────────────────────────────────────────────────────────
build() {
    echo "Building release binary..."
    cd "$PROJECT_ROOT"
    cargo build --release -p calciforge 2>&1 | tail -5
    echo "Build complete."
}

deploy_host() {
    local host="$1"
    echo "── Deploying to $host ──"

    # Create dirs
    run_on "$host" "mkdir -p $INSTALL_DIR/bin $CONFIG_DIR" 2>&1 || {
        echo "  ⚠ Cannot reach $host, skipping"
        return 1
    }

    # Copy binary
    copy_to "$PROJECT_ROOT/target/release/calciforge" "$host" "$INSTALL_DIR/bin/calciforge" 2>&1
    run_on "$host" "chmod +x $INSTALL_DIR/bin/calciforge"

    # Generate default config if it doesn't exist
    if ! run_on "$host" "test -f $CONFIG_DIR/config.toml" 2>/dev/null; then
        echo "  Generating default config.toml..."
        generate_config | run_on "$host" "cat > $CONFIG_DIR/config.toml"
        echo "  ⚠  Edit $CONFIG_DIR/config.toml on $host to set API keys and enable channels"
    else
        echo "  Config already exists — not overwriting"
    fi

    # Install systemd service
    # Note: calciforge reads config from ~/.calciforge/config.toml
    # We symlink /etc/calciforge/config.toml to the expected location
    run_on "$host" "mkdir -p /root/.calciforge && ln -sf $CONFIG_DIR/config.toml /root/.calciforge/config.toml"

    run_on "$host" "cat > /etc/systemd/system/calciforge.service << 'EOF'
[Unit]
Description=Calciforge Gateway
After=network.target

[Service]
Type=simple
ExecStart=$INSTALL_DIR/bin/calciforge
Environment=RUST_LOG=calciforge=info
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable calciforge
systemctl restart calciforge" 2>&1

    echo "  ✅ Deployed to $host"
}

verify_host() {
    local host="$1"
    echo "── Verifying $host ──"

    echo -n "  calciforge:  "
    run_on "$host" "systemctl is-active calciforge 2>/dev/null" || echo "❌ not running"

    echo -n "  config:      "
    if run_on "$host" "test -f $CONFIG_DIR/config.toml" 2>/dev/null; then
        echo "✅ exists"
    else
        echo "❌ missing"
    fi
}

# ── Main ───────────────────────────────────────────────────────────
case "$ACTION" in
    install)
        build
        for host in "${TARGETS[@]}"; do
            deploy_host "$host" || true
        done
        echo ""
        for host in "${TARGETS[@]}"; do
            verify_host "$host"
        done
        echo ""
        echo "=== Installation Complete ==="
        echo "Configure API keys on each host:"
        echo "  export KIMI_API_KEY=..."
        echo "  export OPENAI_API_KEY=sk-..."
        echo "  export ANTHROPIC_API_KEY=sk-ant-..."
        echo ""
        echo "Enable channel scanning in $CONFIG_DIR/config.toml:"
        echo "  scan_messages = true  # per [[channels]] section"
        ;;
    deploy)
        for host in "${TARGETS[@]}"; do
            deploy_host "$host" || true
        done
        ;;
    build)
        build
        ;;
    verify)
        for host in "${TARGETS[@]}"; do
            verify_host "$host"
        done
        ;;
    restart)
        for host in "${TARGETS[@]}"; do
            echo "Restarting calciforge on $host..."
            run_on "$host" "systemctl restart calciforge" 2>&1 || echo "  ⚠ $host unreachable"
        done
        ;;
    status)
        for host in "${TARGETS[@]}"; do
            echo "── $host ──"
            run_on "$host" "systemctl is-active calciforge 2>/dev/null" || echo "  unreachable"
        done
        ;;
    help|*)
        cat << 'USAGE'
Calciforge Binary Installer

Usage:
  scripts/install-calciforge.sh <action> [host1 host2 ...]

Actions:
  install   Build + deploy + configure + verify (full setup)
  deploy    Deploy binary + config + service (skip build)
  build     Just build release binary
  verify    Check service health on targets
  restart   Restart service on targets
  status    Show service status on targets
  help      Show this help

Examples:
  scripts/install-calciforge.sh install 192.168.1.127
  scripts/install-calciforge.sh deploy 192.168.1.127
  scripts/install-calciforge.sh verify 192.168.1.127
  scripts/install-calciforge.sh status

  # Use targets.txt
  echo "192.168.1.127" > scripts/targets.txt
  scripts/install-calciforge.sh install

  # Set custom SSH key
  SSH_KEY=~/.ssh/id_ed25519_librarian scripts/install-calciforge.sh install 192.168.1.127

Channel Scanning Configuration:
  The install script generates a default config.toml with scan_messages = false
  for all channels. To enable scanning, edit config.toml on the target host:
    [[channels]]
    kind = "whatsapp"
    scan_messages = true  # Enable adversary detection for WhatsApp

  HTTP proxy scanning is always-on (no config needed).
USAGE
        ;;
esac
